geometry_msgs/PoseArray goal_poses
int32[] robot_for_goal
---
uint16 error_code
string error_msg
---
geometry_msgs/PoseArray current_poses
builtin_interfaces/Duration navigation_time
int32 num_goals_reached
